name: "Deploy Codigofacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step: 
      run: echo "Pull del codigo"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar version"
